version: '3.7'

services:
  app:
    build:
      context: .
    container_name: api-gateway
    image: gcr.io/summer-hawk-258307/app
    # image: wagubib/microservice:apigateway
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3072:3001"
    networks:
      - auth-service_default
networks:
  auth-service_default:
    external: true
